# -*- coding: utf-8 -*-
"""runtime_security_analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fW3_IIQi4iJ4bXF1KSEt9HRx8PPNoOLi
"""

import random
import pandas as pd
import numpy as np
from sklearn.ensemble import IsolationForest
from sentence_transformers import SentenceTransformer
import faiss

def generate_logs(n=600):
    processes = ["nginx", "python", "redis", "node", "bash", "curl"]
    actions = ["read", "write", "connect", "exec", "delete"]
    logs = []
    for i in range(n):
        entry = {
            "pid": random.randint(1000, 6000),
            "process": random.choice(processes),
            "action": random.choice(actions),
            "bytes": random.randint(20, 12000),
            "timestamp": i
        }
        if random.random() < 0.06:
            entry["bytes"] = random.randint(60000, 200000)
            entry["process"] = "unknown_binary"
        logs.append(entry)
    return pd.DataFrame(logs)

df = generate_logs()
print("total runtime events:", len(df))

model = IsolationForest(contamination=0.06, random_state=42)
df["anomaly"] = model.fit_predict(df[["bytes"]])
anomalies = df[df["anomaly"] == -1]
print("detected suspicious events:", len(anomalies))

def log_to_text(row):
    return f"process {row.process} performed {row.action} with {row.bytes} bytes"

texts = anomalies.apply(log_to_text, axis=1).tolist()

embedder = SentenceTransformer("all-MiniLM-L6-v2")
vectors = embedder.encode(texts)

dim = vectors.shape[1]
index = faiss.IndexFlatL2(dim)
index.add(np.array(vectors))
print("stored threat vectors:", index.ntotal)

def search_threats(query, top_k=3):
    query_vec = embedder.encode([query])
    distances, indices = index.search(np.array(query_vec), top_k)
    print("\nsearch:", query)
    for idx in indices[0]:
        print(texts[idx])

search_threats("suspicious file deletion")
search_threats("unknown process using high memory")
search_threats("malware sending data")

print("\nruntime security analysis completed")