# -*- coding: utf-8 -*-
"""security_event_store.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YvaO9XRfCAVW5mhyI5ALFX9_Hvxecr6m
"""

import sqlite3
import hashlib
import time
import random
import json

conn = sqlite3.connect("security.db")
cur = conn.cursor()

cur.execute("pragma foreign_keys = on")

cur.executescript("""
create table if not exists containers (
    container_id text primary key,
    image text,
    namespace text,
    created_at integer
);

create table if not exists processes (
    pid integer,
    container_id text,
    name text,
    primary key (pid, container_id),
    foreign key (container_id) references containers(container_id)
);

create table if not exists events (
    event_id text primary key,
    pid integer,
    container_id text,
    action text,
    bytes integer,
    timestamp integer,
    hash text,
    foreign key (pid, container_id) references processes(pid, container_id)
);

create table if not exists anomalies (
    event_id text primary key,
    score real,
    severity text,
    foreign key (event_id) references events(event_id)
);

create index if not exists idx_events_container on events(container_id);
create index if not exists idx_events_action on events(action);
create index if not exists idx_anomalies_severity on anomalies(severity);
""")

containers = ["c1", "c2", "c3"]
images = ["nginx:v1", "python:v2", "redis:v3"]

for c in containers:
    cur.execute("insert or ignore into containers values (?, ?, ?, ?)", (
        c, random.choice(images), "prod", int(time.time())
    ))

processes = ["nginx", "python", "redis", "curl", "bash", "unknown_binary"]

for c in containers:
    for i in range(5):
        cur.execute("insert or ignore into processes values (?, ?, ?)", (
            random.randint(1000, 9000), c, random.choice(processes)
        ))

def make_event(pid, container, action, size):
    payload = f"{pid}{container}{action}{size}{time.time()}"
    h = hashlib.sha256(payload.encode()).hexdigest()
    return h

for _ in range(500):
    container = random.choice(containers)
    cur.execute("select pid from processes where container_id = ? order by random() limit 1", (container,))
    pid = cur.fetchone()[0]
    action = random.choice(["read", "write", "exec", "connect", "delete"])
    size = random.randint(10, 12000)

    if random.random() < 0.05:
        size = random.randint(60000, 200000)
        action = "exec"

    eid = make_event(pid, container, action, size)

    cur.execute("insert into events values (?, ?, ?, ?, ?, ?, ?)", (
        eid, pid, container, action, size, int(time.time()), eid[:16]
    ))

    if size > 50000:
        severity = "high"
        score = random.uniform(0.8, 1.0)
        cur.execute("insert into anomalies values (?, ?, ?)", (eid, score, severity))

conn.commit()

cur.execute("""
select c.container_id, count(a.event_id)
from containers c
left join events e on c.container_id = e.container_id
left join anomalies a on e.event_id = a.event_id
group by c.container_id
""")

print("threats per container")
for row in cur.fetchall():
    print(row)

cur.execute("""
select e.container_id, e.pid, e.action, e.bytes, a.severity
from events e
join anomalies a on e.event_id = a.event_id
order by e.bytes desc
limit 10
""")

print("\nmost dangerous runtime events")
for r in cur.fetchall():
    print(r)

cur.execute("""
select e.container_id, json_group_array(e.action)
from events e
where e.bytes > 50000
group by e.container_id
""")

print("\nattack surface by container")
for r in cur.fetchall():
    print(r)

conn.close()